### PR TITLE
Replaced library and fix the MissingInformationToCreateTransaction bug in AfterPay

### PR DESCRIPTION
**Pull request by LeasoftKonstantinShapoval**

### CODE REVIEW

**Comment by LeasoftKonstantinShapoval** [comment]
Review the Fix of the MissingInformationToCreateTransaction(400): Billing address required.

**Comment by LeasoftKonstantinShapoval** [comment]
Review the code refactoring.

**Review by tiutiunnykleasoft — COMMENTED** [review]
Version changes are required

**Comment by LeasoftKonstantinShapoval** [comment]
Version changes completed.

**Review by tiutiunnykleasoft — APPROVED** [review]
OK.

**Pull request merged**
